modLoader="javafml"
license="All Rights Reserved"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/Glitchfiend/BiomesOPlenty/issues"
displayURL="https://minecraft.curseforge.com/projects/biomes-o-plenty"
logoFile="bop_logo.png"

[[mods]]
    modId="biomesoplenty"
    version="${file.jarVersion}"
    displayName="Biomes O' Plenty"
	authors="Forstride, Adubbz"
	credits="LudoCrypt, Tim Rurkowski, cheeserolls, ted80"
    description="Adds over 50 new biomes, blocks, and more!"

[[dependencies.biomesoplenty]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.biomesoplenty]]
    modId="terrablender"
    mandatory=true
    versionRange="[2.2.0.154,)"
    ordering="AFTER"
    side="BOTH"
